//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class eng {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal eng() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RM.Resources.eng", typeof(eng).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RoomFinishes plugin developed by Gregory Yakovlev
        ///
        ///LICENSE AGREEMENT.
        ///This software is protected by national copyright laws and international treaties. The exclusive rights to use this program belong to its author / publisher.
        ///
        ///The program and its components can be used for free, without license fees, for an unlimited time.
        ///
        ///Commercial distribution of the program is prohibited. (It is forbidden to take money for distributing the program).
        ///
        ///The software is supplied &quot;as is&quot;.
        ///
        ///The program can be inc [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string About_Text {
            get {
                return ResourceManager.GetString("About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        internal static string aboutTitle_ribbonPanel {
            get {
                return ResourceManager.GetString("aboutTitle_ribbonPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Floor finish top height.
        /// </summary>
        internal static string floor_groupboxName {
            get {
                return ResourceManager.GetString("floor_groupboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select rooms for installing floor finishes.
        /// </summary>
        internal static string floor_groupboxRoomSelectName {
            get {
                return ResourceManager.GetString("floor_groupboxRoomSelectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From level.
        /// </summary>
        internal static string floor_height_label {
            get {
                return ResourceManager.GetString("floor_height_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value from parameter.
        /// </summary>
        internal static string floor_height_param_label {
            get {
                return ResourceManager.GetString("floor_height_param_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter the correct height of the floor finishes.
        /// </summary>
        internal static string floor_heightValueError {
            get {
                return ResourceManager.GetString("floor_heightValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There is no room in the current model.
        /// </summary>
        internal static string floor_noRoomError {
            get {
                return ResourceManager.GetString("floor_noRoomError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a floor type.
        /// </summary>
        internal static string floor_select_floor_label {
            get {
                return ResourceManager.GetString("floor_select_floor_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create floor finishes.
        /// </summary>
        internal static string floor_TaskDialogName {
            get {
                return ResourceManager.GetString("floor_TaskDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Floor finish.
        /// </summary>
        internal static string floor_transactionName {
            get {
                return ResourceManager.GetString("floor_transactionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Command is failed for unexpected reason..
        /// </summary>
        internal static string floor_unexpectedError {
            get {
                return ResourceManager.GetString("floor_unexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Floor finishes.
        /// </summary>
        internal static string floorTitle_ribbonPanel {
            get {
                return ResourceManager.GetString("floorTitle_ribbonPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rooms finishes.
        /// </summary>
        internal static string groupTitle_ribbonPanel {
            get {
                return ResourceManager.GetString("groupTitle_ribbonPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Elevation.
        /// </summary>
        internal static string levelTag_parameter_group {
            get {
                return ResourceManager.GetString("levelTag_parameter_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The command failed because no rooms were found. Try changing to a different view and running the command again..
        /// </summary>
        internal static string roomAutoSelectError {
            get {
                return ResourceManager.GetString("roomAutoSelectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All rooms in current view.
        /// </summary>
        internal static string roomFinishes_all_rooms_radio {
            get {
                return ResourceManager.GetString("roomFinishes_all_rooms_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string roomFinishes_Cancel_Button {
            get {
                return ResourceManager.GetString("roomFinishes_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculation based on room level.
        /// </summary>
        internal static string roomFinishes_from_level_Radio {
            get {
                return ResourceManager.GetString("roomFinishes_from_level_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The upper limit of the walls of the rooms finishes.
        /// </summary>
        internal static string roomFinishes_groupboxParamName {
            get {
                return ResourceManager.GetString("roomFinishes_groupboxParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The choice of rooms for the installation of walls finishes.
        /// </summary>
        internal static string roomFinishes_groupboxRoomName {
            get {
                return ResourceManager.GetString("roomFinishes_groupboxRoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        internal static string roomFinishes_height_textBox {
            get {
                return ResourceManager.GetString("roomFinishes_height_textBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter a height value for the walls finishes.
        /// </summary>
        internal static string roomFinishes_heightValueError {
            get {
                return ResourceManager.GetString("roomFinishes_heightValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        internal static string roomFinishes_OK_Button {
            get {
                return ResourceManager.GetString("roomFinishes_OK_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Room finishes.
        /// </summary>
        internal static string roomFinishes_ribbon_panel_name {
            get {
                return ResourceManager.GetString("roomFinishes_ribbon_panel_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a wall type for a skirting board :.
        /// </summary>
        internal static string roomFinishes_select_wall_label {
            get {
                return ResourceManager.GetString("roomFinishes_select_wall_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only selected rooms.
        /// </summary>
        internal static string roomFinishes_selected_rooms_radio {
            get {
                return ResourceManager.GetString("roomFinishes_selected_rooms_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select rooms.
        /// </summary>
        internal static string roomFinishes_SelectRooms {
            get {
                return ResourceManager.GetString("roomFinishes_SelectRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creating walls finishes.
        /// </summary>
        internal static string roomFinishes_TaskDialogName {
            get {
                return ResourceManager.GetString("roomFinishes_TaskDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculation from the height of the room.
        /// </summary>
        internal static string roomFinishes_to_height_Radio {
            get {
                return ResourceManager.GetString("roomFinishes_to_height_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a finishes walls.
        /// </summary>
        internal static string roomFinishes_transactionName {
            get {
                return ResourceManager.GetString("roomFinishes_transactionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Command is failed for unexpected reason..
        /// </summary>
        internal static string roomFinishes_unexpectedError {
            get {
                return ResourceManager.GetString("roomFinishes_unexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This function will not work on wall type with a vertically compound structure..
        /// </summary>
        internal static string roomFinishes_verticallyCompoundError {
            get {
                return ResourceManager.GetString("roomFinishes_verticallyCompoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No fit-out has been done as no rooms have been selected..
        /// </summary>
        internal static string roomSelectError {
            get {
                return ResourceManager.GetString("roomSelectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Room selection error.
        /// </summary>
        internal static string roomSelectError_TitleDialogBox {
            get {
                return ResourceManager.GetString("roomSelectError_TitleDialogBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rooms finishes.
        /// </summary>
        internal static string titlePanel {
            get {
                return ResourceManager.GetString("titlePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Walls finishes.
        /// </summary>
        internal static string wallTitle_ribbonPanel {
            get {
                return ResourceManager.GetString("wallTitle_ribbonPanel", resourceCulture);
            }
        }
    }
}
