//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class rus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RM.Resources.rus", typeof(rus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отметка верха пола.
        /// </summary>
        internal static string floor_groupboxName {
            get {
                return ResourceManager.GetString("floor_groupboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор помещений для установки отделки пола.
        /// </summary>
        internal static string floor_groupboxRoomSelectName {
            get {
                return ResourceManager.GetString("floor_groupboxRoomSelectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От уровня.
        /// </summary>
        internal static string floor_height_label {
            get {
                return ResourceManager.GetString("floor_height_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение из параметра.
        /// </summary>
        internal static string floor_height_param_label {
            get {
                return ResourceManager.GetString("floor_height_param_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите корректное значение высоты пола.
        /// </summary>
        internal static string floor_heightValueError {
            get {
                return ResourceManager.GetString("floor_heightValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В данной модели нет места.
        /// </summary>
        internal static string floor_noRoomError {
            get {
                return ResourceManager.GetString("floor_noRoomError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напольные покрытия.
        /// </summary>
        internal static string floor_ribbon_panel_name {
            get {
                return ResourceManager.GetString("floor_ribbon_panel_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор типа пола отделки.
        /// </summary>
        internal static string floor_select_floor_label {
            get {
                return ResourceManager.GetString("floor_select_floor_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание отделки пола.
        /// </summary>
        internal static string floor_TaskDialogName {
            get {
                return ResourceManager.GetString("floor_TaskDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать тип отделки ????.
        /// </summary>
        internal static string floor_toolTip {
            get {
                return ResourceManager.GetString("floor_toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отделка пола.
        /// </summary>
        internal static string floor_transactionName {
            get {
                return ResourceManager.GetString("floor_transactionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда не выполнена по непредвиденной причине..
        /// </summary>
        internal static string floor_unexpectedError {
            get {
                return ResourceManager.GetString("floor_unexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to максимальная высота низа?.
        /// </summary>
        internal static string levelTag_bottom_elevation_max {
            get {
                return ResourceManager.GetString("levelTag_bottom_elevation_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная высота низа?.
        /// </summary>
        internal static string levelTag_bottom_elevation_min {
            get {
                return ResourceManager.GetString("levelTag_bottom_elevation_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высота.
        /// </summary>
        internal static string levelTag_parameter_group {
            get {
                return ResourceManager.GetString("levelTag_parameter_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная высота верха?.
        /// </summary>
        internal static string levelTag_top_elevation_max {
            get {
                return ResourceManager.GetString("levelTag_top_elevation_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная высота верха?.
        /// </summary>
        internal static string levelTag_top_elevation_min {
            get {
                return ResourceManager.GetString("levelTag_top_elevation_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все помещения на текущем виде.
        /// </summary>
        internal static string roomFinishes_all_rooms_radio {
            get {
                return ResourceManager.GetString("roomFinishes_all_rooms_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смещение.
        /// </summary>
        internal static string roomFinishes_board_height_label {
            get {
                return ResourceManager.GetString("roomFinishes_board_height_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стена.
        /// </summary>
        internal static string roomFinishes_button_name {
            get {
                return ResourceManager.GetString("roomFinishes_button_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        internal static string roomFinishes_Cancel_Button {
            get {
                return ResourceManager.GetString("roomFinishes_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчет от уровня помещения.
        /// </summary>
        internal static string roomFinishes_from_level_Radio {
            get {
                return ResourceManager.GetString("roomFinishes_from_level_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верхний предел стен отделки помещений.
        /// </summary>
        internal static string roomFinishes_groupboxParamName {
            get {
                return ResourceManager.GetString("roomFinishes_groupboxParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор помещений для установки стен отделки.
        /// </summary>
        internal static string roomFinishes_groupboxRoomName {
            get {
                return ResourceManager.GetString("roomFinishes_groupboxRoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string roomFinishes_height_textBox {
            get {
                return ResourceManager.GetString("roomFinishes_height_textBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите значение высоты отделки стен.
        /// </summary>
        internal static string roomFinishes_heightValueError {
            get {
                return ResourceManager.GetString("roomFinishes_heightValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string roomFinishes_OK_Button {
            get {
                return ResourceManager.GetString("roomFinishes_OK_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отделка помещений.
        /// </summary>
        internal static string roomFinishes_ribbon_panel_name {
            get {
                return ResourceManager.GetString("roomFinishes_ribbon_panel_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор типа стены для отделки.
        /// </summary>
        internal static string roomFinishes_select_wall_label {
            get {
                return ResourceManager.GetString("roomFinishes_select_wall_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только выбранные помещения.
        /// </summary>
        internal static string roomFinishes_selected_rooms_radio {
            get {
                return ResourceManager.GetString("roomFinishes_selected_rooms_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите помещения.
        /// </summary>
        internal static string roomFinishes_SelectRooms {
            get {
                return ResourceManager.GetString("roomFinishes_SelectRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание стен отделки помещений.
        /// </summary>
        internal static string roomFinishes_TaskDialogName {
            get {
                return ResourceManager.GetString("roomFinishes_TaskDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчет от высоты помещения.
        /// </summary>
        internal static string roomFinishes_to_height_Radio {
            get {
                return ResourceManager.GetString("roomFinishes_to_height_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать стены отделки помещений.
        /// </summary>
        internal static string roomFinishes_toolTip {
            get {
                return ResourceManager.GetString("roomFinishes_toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать стены отделки помещений.
        /// </summary>
        internal static string roomFinishes_transactionName {
            get {
                return ResourceManager.GetString("roomFinishes_transactionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда не выполнена по непредвиденной причине.
        /// </summary>
        internal static string roomFinishes_unexpectedError {
            get {
                return ResourceManager.GetString("roomFinishes_unexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта функция не будет работать с составной стеной.
        /// </summary>
        internal static string roomFinishes_verticallyCompoundError {
            get {
                return ResourceManager.GetString("roomFinishes_verticallyCompoundError", resourceCulture);
            }
        }
    }
}
