//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class rus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rus() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RM.Resources.rus", typeof(rus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Плагин RoomFinish разработан Григорием Яковлевым
        ///
        ///ЛИЦЕНЗИОННОЕ СОГЛАШЕНИЕ.
        ///Эта программа защищена национальными законами и международными соглашениями об авторском праве. Исключительные права на использование этой программой принадлежат ее автору/издателю.
        ///
        ///Программой и ее компонентами можно пользоваться бесплатно, без лицензионных отчислений неограниченное время.
        ///
        ///Запрещено коммерческое распространение программы. (За распространение программы запрещено брать деньги).
        ///
        ///Программа поставляется &quot;как е [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string About_Text {
            get {
                return ResourceManager.GetString("About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        internal static string aboutTitle_ribbonPanel {
            get {
                return ResourceManager.GetString("aboutTitle_ribbonPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отметка верха отделки пола.
        /// </summary>
        internal static string floor_groupboxName {
            get {
                return ResourceManager.GetString("floor_groupboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор помещений для установки отделки пола.
        /// </summary>
        internal static string floor_groupboxRoomSelectName {
            get {
                return ResourceManager.GetString("floor_groupboxRoomSelectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От уровня.
        /// </summary>
        internal static string floor_height_label {
            get {
                return ResourceManager.GetString("floor_height_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение из параметра.
        /// </summary>
        internal static string floor_height_param_label {
            get {
                return ResourceManager.GetString("floor_height_param_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, введите корректное значение высоты отделки пола.
        /// </summary>
        internal static string floor_heightValueError {
            get {
                return ResourceManager.GetString("floor_heightValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В данной модели нет места.
        /// </summary>
        internal static string floor_noRoomError {
            get {
                return ResourceManager.GetString("floor_noRoomError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор типа перекрытия для отделки пола.
        /// </summary>
        internal static string floor_select_floor_label {
            get {
                return ResourceManager.GetString("floor_select_floor_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание отделки пола.
        /// </summary>
        internal static string floor_TaskDialogName {
            get {
                return ResourceManager.GetString("floor_TaskDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отделка пола.
        /// </summary>
        internal static string floor_transactionName {
            get {
                return ResourceManager.GetString("floor_transactionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Команда не выполнена по непредвиденной причине..
        /// </summary>
        internal static string floor_unexpectedError {
            get {
                return ResourceManager.GetString("floor_unexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отделка пола.
        /// </summary>
        internal static string floorTitle_ribbonPanel {
            get {
                return ResourceManager.GetString("floorTitle_ribbonPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отделка помещений.
        /// </summary>
        internal static string groupTitle_ribbonPanel {
            get {
                return ResourceManager.GetString("groupTitle_ribbonPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высота.
        /// </summary>
        internal static string levelTag_parameter_group {
            get {
                return ResourceManager.GetString("levelTag_parameter_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Команда не выполнена, так как не было найдено ни одного помещения. Попробуйте перейти на другой вид и выполнить команду еще раз..
        /// </summary>
        internal static string roomAutoSelectError {
            get {
                return ResourceManager.GetString("roomAutoSelectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все помещения на текущем виде.
        /// </summary>
        internal static string roomFinishes_all_rooms_radio {
            get {
                return ResourceManager.GetString("roomFinishes_all_rooms_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить.
        /// </summary>
        internal static string roomFinishes_Cancel_Button {
            get {
                return ResourceManager.GetString("roomFinishes_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расчет от уровня помещения.
        /// </summary>
        internal static string roomFinishes_from_level_Radio {
            get {
                return ResourceManager.GetString("roomFinishes_from_level_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Верхний предел стен отделки помещений.
        /// </summary>
        internal static string roomFinishes_groupboxParamName {
            get {
                return ResourceManager.GetString("roomFinishes_groupboxParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор помещений для установки стен отделки.
        /// </summary>
        internal static string roomFinishes_groupboxRoomName {
            get {
                return ResourceManager.GetString("roomFinishes_groupboxRoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        internal static string roomFinishes_height_textBox {
            get {
                return ResourceManager.GetString("roomFinishes_height_textBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, введите значение высоты отделки стен.
        /// </summary>
        internal static string roomFinishes_heightValueError {
            get {
                return ResourceManager.GetString("roomFinishes_heightValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        internal static string roomFinishes_OK_Button {
            get {
                return ResourceManager.GetString("roomFinishes_OK_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отделка помещений.
        /// </summary>
        internal static string roomFinishes_ribbon_panel_name {
            get {
                return ResourceManager.GetString("roomFinishes_ribbon_panel_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор типа стены для отделки.
        /// </summary>
        internal static string roomFinishes_select_wall_label {
            get {
                return ResourceManager.GetString("roomFinishes_select_wall_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только выбранные помещения.
        /// </summary>
        internal static string roomFinishes_selected_rooms_radio {
            get {
                return ResourceManager.GetString("roomFinishes_selected_rooms_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите помещения.
        /// </summary>
        internal static string roomFinishes_SelectRooms {
            get {
                return ResourceManager.GetString("roomFinishes_SelectRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание стен отделки помещений.
        /// </summary>
        internal static string roomFinishes_TaskDialogName {
            get {
                return ResourceManager.GetString("roomFinishes_TaskDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расчет от высоты помещения.
        /// </summary>
        internal static string roomFinishes_to_height_Radio {
            get {
                return ResourceManager.GetString("roomFinishes_to_height_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать стены отделки помещений.
        /// </summary>
        internal static string roomFinishes_transactionName {
            get {
                return ResourceManager.GetString("roomFinishes_transactionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Команда не выполнена по непредвиденной причине.
        /// </summary>
        internal static string roomFinishes_unexpectedError {
            get {
                return ResourceManager.GetString("roomFinishes_unexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта функция не будет работать с составной стеной.
        /// </summary>
        internal static string roomFinishes_verticallyCompoundError {
            get {
                return ResourceManager.GetString("roomFinishes_verticallyCompoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отделка не выполнена, так как не было выбрано ни одного помещения..
        /// </summary>
        internal static string roomSelectError {
            get {
                return ResourceManager.GetString("roomSelectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка выбора помещений.
        /// </summary>
        internal static string roomSelectError_TitleDialogBox {
            get {
                return ResourceManager.GetString("roomSelectError_TitleDialogBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отделка помещений.
        /// </summary>
        internal static string titlePanel {
            get {
                return ResourceManager.GetString("titlePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отделка стен.
        /// </summary>
        internal static string wallTitle_ribbonPanel {
            get {
                return ResourceManager.GetString("wallTitle_ribbonPanel", resourceCulture);
            }
        }
    }
}
